## Run on trusty environment as solr dies all the time on containers after travis move to gce
sudo: required
dist: trusty

# Workaround for the issue found in the stable image promoted on Dec 1, 2016.
# See https://github.com/travis-ci/travis-ci/issues/6928#issuecomment-264227708
group: deprecated

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
    include:
        - php: 7.0
          env: TEST_CONFIG="phpunit.xml"
        - php: 5.6
          env: TEST_CONFIG="phpunit-integration-legacy-solr.xml" SOLR_VERSION="6.3.0"  CORES_SETUP="dedicated"
        - php: 5.6
          env: TEST_CONFIG="phpunit-integration-legacy-solr.xml" SOLR_VERSION="6.3.0"  CORES_SETUP="shared"
        - php: 7.0
          env: TEST_CONFIG="phpunit-integration-legacy-solr.xml" SOLR_VERSION="6.3.0"  CORES_SETUP="single" SOLR_CORES="collection1"

# test only master and stable branches (+ Pull requests against those)
branches:
    only:
        - master
        - /^\d.\d+$/

before_script:
    - phpenv config-rm xdebug.ini
    # Setup GitHub key to avoid api rate limit (pure auth read only key, no rights, for use by ezsystems repos only!)
    - composer config -g github-oauth.github.com "d0285ed5c8644f30547572ead2ed897431c1fc09"
    # Avoid memory issues on composer install
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - travis_retry composer update --prefer-dist --no-interaction
    - if [ "$SOLR_VERSION" != "" ] ; then ./bin/.travis/init_solr.sh ; fi

script:
    - if [ "$SOLR_VERSION" = "" ] ; then php vendor/bin/phpunit --bootstrap tests/bootstrap.php -c $TEST_CONFIG ; fi
    - if [ "$SOLR_VERSION" != "" ] ; then php -d memory_limit=-1 vendor/bin/phpunit --bootstrap tests/bootstrap.php -c vendor/ezsystems/ezpublish-kernel/$TEST_CONFIG ; fi

notifications:
    email: false
