language: php

matrix:
    include:
        - php: 5.6
          env: TEST_CONFIG="phpunit.xml"
        - php: 5.4
          env: TEST_CONFIG="phpunit-integration-legacy-solr.xml" SOLR_VERSION="4.10.4" CORES_SETUP="dedicated" SOLR_CORES="core0 core1 core2 core3 core4 core5 core6 core7" SOLR_CONFS="lib/eZ/Publish/Core/Search/Solr/Content/Resources/schema.xml"
        - php: 5.5
          env: TEST_CONFIG="phpunit-integration-legacy-solr.xml" SOLR_VERSION="4.10.4" CORES_SETUP="shared" SOLR_CORES="core0 core1 core2 core3 core4" SOLR_CONFS="lib/eZ/Publish/Core/Search/Solr/Content/Resources/schema.xml"
        - php: 5.6
          env: TEST_CONFIG="phpunit-integration-legacy-solr.xml" SOLR_VERSION="4.10.4" CORES_SETUP="single" SOLR_CONFS="lib/eZ/Publish/Core/Search/Solr/Content/Resources/schema.xml"

# test only master (+ Pull requests)
branches:
    only:
        - master

before_script:
    - composer selfupdate
    - composer install --prefer-source
    - if [ "$SOLR_VERSION" != "" ] ; then ./bin/.travis/init_solr.sh ; fi

script:
    - if [ "$SOLR_VERSION" = "" ] ; then php vendor/bin/phpunit --bootstrap tests/bootstrap.php -c $TEST_CONFIG ; fi
    - if [ "$SOLR_VERSION" != "" ] ; then php -d memory_limit=-1 vendor/bin/phpunit --bootstrap tests/bootstrap.php -c vendor/ezsystems/ezpublish-kernel/$TEST_CONFIG ; fi

notifications:
    email: false
