## Run on trusty environment as solr dies all the time on containers after travis move to gce
sudo: required
dist: trusty

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

env:
    global:
        - COMPOSER_MEMORY_LIMIT=6G

matrix:
    include:
        - php: 7.2
          env: TEST_CONFIG="phpunit.xml"
        - php: 7.1
          env: TEST_CONFIG="phpunit-integration-legacy-solr.xml" SOLR_VERSION="7.7.2"  CORES_SETUP="dedicated"
        - php: 7.1
          env: TEST_CONFIG="phpunit-integration-legacy-solr.xml" SOLR_VERSION="7.7.2"  CORES_SETUP="shared"
        - php: 7.1
          env: TEST_CONFIG="phpunit-integration-legacy-solr.xml" SOLR_VERSION="7.7.2"  CORES_SETUP="single" SOLR_CORES="collection1"
        - php: 7.1
          env: TEST_CONFIG="phpunit-integration-legacy-solr.xml" SOLR_VERSION="7.7.2"  CORES_SETUP="cloud" SOLR_CLOUD="yes"
        # Solr 8.5.2
        - php: 7.1
          env: TEST_CONFIG="phpunit-integration-legacy-solr.xml" SOLR_VERSION="8.5.2"  CORES_SETUP="dedicated"
        - php: 7.1
          env: TEST_CONFIG="phpunit-integration-legacy-solr.xml" SOLR_VERSION="8.5.2"  CORES_SETUP="shared"
        - php: 7.1
          env: TEST_CONFIG="phpunit-integration-legacy-solr.xml" SOLR_VERSION="8.5.2"  CORES_SETUP="single" SOLR_CORES="collection1"
        - php: 7.1
          env: TEST_CONFIG="phpunit-integration-legacy-solr.xml" SOLR_VERSION="8.5.2"  CORES_SETUP="cloud" SOLR_CLOUD="yes"
# test only master and stable branches (+ Pull requests against those)
branches:
    only:
        - master
        - /^\d.\d+$/

before_script:
    - phpenv config-rm xdebug.ini
    # Setup GitHub key to avoid api rate limit (pure auth read only key, no rights, for use by ezsystems repos only!)
    - composer config -g github-oauth.github.com "d0285ed5c8644f30547572ead2ed897431c1fc09"
    # Avoid memory issues on composer install
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - ./bin/.travis/enable_swap.sh
    - if [ "$COMPOSER_REQUIRE" != "" ] ; then composer require --no-update $COMPOSER_REQUIRE ; fi
    - travis_retry composer update --prefer-dist --no-interaction
    - if [ "$SOLR_VERSION" != "" ] ; then ./bin/.travis/init_solr.sh ; fi

script:
    - if [ "$SOLR_VERSION" = "" ] ; then php vendor/bin/phpunit --bootstrap tests/bootstrap.php -c $TEST_CONFIG ; fi
    - if [ "$SOLR_VERSION" != "" ] ; then php -d memory_limit=-1 vendor/bin/phpunit --bootstrap tests/bootstrap.php -c vendor/ezsystems/ezpublish-kernel/$TEST_CONFIG ; fi

notifications:
  slack:
    rooms:
      - secure: F+SDUD8se903A7MZlEOr5JdQzVI6EcEmMxEe/Y8v8kX4HKl7VuzqHpLHoJAVbuP/P8rGwOojn9VIeCxs6vemn9sV+MWEMleaet+nZ+sxi7cZwT3VWG8LuKIWueVsbl9WU8S5i0iiafN96Tf8ZWIOAz8cAFqL0V6LDFeM7cIP7ENbcR7d52Key7MXej1X5Ssee1HnMVx+doQfYCxIXEYmtSHMRCNX/67ClvjzI6/OPLQJ/Wb60vMxpxdoxdSWs6hF9joHMTqRe6i4h8cmHr1Z6yRtmP48i+Nzp7Dg0JdPV4oJjXzRzKjDQhfRzMjdRbEaevLOVai8wwpICfzWHobF2DS9lnUt+JgPH6eK+tT4YEkvpqY/Sw/KlClF8BhDYQgEGTF9zS4mX/tWhCdajIiY80PrpsIoZ8cRtbTENJ83EUqk4T4x2jh91qnXQ1NhvwCg4SCPQ1rsJ9/XoTrjBsvQeVSgXVh9+a3WAsEttqk9+kOw2vCU2iIe21MRxFyb3RVb6kXm8pTcWJvCkc7FdhIjfxFdzqqdgO2LBfvCqZW0E4CMrfB1VUJXYVZbYoCw+5w3Fdtcxko6lYFWl0SHSO8anU6wIc5aMe4vn09Dv0brhRmEXsJTHs43QgTcqk2L7B2VAyyIXARR6mxCu1tc/3wS0BrYaeEWQ1E3lBI6riNYWbk=
    on_success: change
    on_failure: always
    on_pull_requests: false
